### ISSUE TITLE
Check Team Project 2 Submission

### ISSUE THREAD

**Issue by DavidDr90** [DavidDr90/Hadasa-Rehabilitation#2]
We work to complete the second Team Assignment, from the link:
https://github.com/jce-il/se-class-materials/blob/master/docs/team/proj2-inception.md

**Due to Sunday Murch 25th.**

## Tasks Distribution:

- All - Every one need to add at least two rows to the Risk Managment Table in the Inception wiki page.
- David - Readme and Inception.
- Alex - Add info in the Readme file.
- Ofek - Draw an Architecture diagram, section 8 under the Planing Page.
- Dor - Team page in the wiki.
- Or - Inception page in the wiki, all the section except 3 and 8.

**Comment by eranhd** [comment]
great! done.
